install:
  - yarn

script:
  - yarn lint

build:
  - yarn build

deploy:
  provider: npm
  email: '$DEPLOY_EMAIL'
  api_key: '$DEPLOY_TOKEN'
  skip_cleanup: true
  on:
    tags: true
    branch: production
